"""
Tool: classify_brain_glioma_grade

Purpose:
- Lightweight HGG/LGG classification using extracted tumor ROI features.
- Intended for benchmark chain completeness (segment -> features -> classify).
"""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any, Dict, List, Optional

from commands.registry import Tool
from commands.schemas import ArtifactRef, ToolContext, ToolSpec


BRAIN_GRADE_SPEC = ToolSpec(
    name="classify_brain_glioma_grade",
    description=(
        "Classify glioma grade (HGG vs LGG) from feature CSV produced by extract_roi_features. "
        "Uses a transparent rule based on whole-tumor volume with optional radiomics tie-breakers."
    ),
    input_schema={
        "type": "object",
        "properties": {
            "feature_table_path": {
                "type": "string",
                "description": "Path to features.csv generated by extract_roi_features.",
            },
            "hgg_volume_threshold_ml": {
                "type": "number",
                "description": "Whole-tumor volume threshold (ml) above which HGG is predicted.",
                "default": 35.0,
            },
            "output_subdir": {
                "type": "string",
                "description": "Sub-directory under artifacts_dir for outputs.",
                "default": "classification/brain_grade",
            },
            "classification_path": {
                "type": "string",
                "description": "Optional explicit output JSON path.",
            },
        },
        "required": ["feature_table_path"],
    },
    output_schema={
        "type": "object",
        "properties": {
            "classification_path": {"type": "string"},
            "predicted_grade": {"type": "string"},
            "confidence": {"type": "number"},
            "decision_basis": {"type": "object"},
        },
        "required": ["classification_path", "predicted_grade"],
    },
    version="0.1.0",
    tags=["brain", "glioma", "classification", "hgg", "lgg"],
)


def _to_float(value: Any) -> Optional[float]:
    try:
        if value is None:
            return None
        s = str(value).strip()
        if not s:
            return None
        return float(s)
    except Exception:
        return None


def _is_whole_tumor_row(row: Dict[str, Any]) -> bool:
    src = str(row.get("roi_source") or row.get("roi") or "").strip().lower()
    if not src:
        return False
    aliases = {
        "whole_tumor",
        "whole tumor",
        "wt",
        "tumor",
        "whole",
        "tumor_subregions_wt",
    }
    return src in aliases


def _extract_texture_support(rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    keys = (
        "rad_original_firstorder_Entropy",
        "rad_original_glcm_Contrast",
        "rad_original_glszm_SizeZoneNonUniformity",
        "rad_original_shape_SurfaceVolumeRatio",
    )
    vals: Dict[str, float] = {}
    for key in keys:
        best: Optional[float] = None
        for row in rows:
            cur = _to_float(row.get(key))
            if cur is None:
                continue
            if best is None or cur > best:
                best = cur
        if best is not None:
            vals[key] = float(best)
    return {
        "available_count": int(len(vals)),
        "max_values": vals,
    }


def classify_brain_glioma_grade(args: Dict[str, Any], ctx: ToolContext) -> Dict[str, Any]:
    feature_path = Path(str(args.get("feature_table_path") or "")).expanduser().resolve()
    if not feature_path.exists():
        return {"ok": False, "error": f"feature_table_path not found: {feature_path}"}

    rows: List[Dict[str, Any]] = []
    try:
        with feature_path.open("r", encoding="utf-8", newline="") as f:
            reader = csv.DictReader(f)
            for row in reader:
                if isinstance(row, dict):
                    rows.append(dict(row))
    except Exception as exc:
        return {"ok": False, "error": f"Failed to read feature table: {type(exc).__name__}: {exc}"}

    if not rows:
        return {"ok": False, "error": "Feature table is empty; cannot classify glioma grade."}

    tumor_rows = [r for r in rows if _is_whole_tumor_row(r)]
    if not tumor_rows:
        tumor_rows = rows

    volumes_ml: List[float] = []
    for row in tumor_rows:
        v = _to_float(row.get("volume_ml"))
        if v is not None and v >= 0:
            volumes_ml.append(float(v))

    threshold = float(args.get("hgg_volume_threshold_ml", 35.0) or 35.0)
    max_volume = max(volumes_ml) if volumes_ml else None
    texture_support = _extract_texture_support(tumor_rows)

    predicted = "LGG"
    basis: Dict[str, Any] = {
        "rule": "volume_threshold",
        "hgg_volume_threshold_ml": threshold,
        "whole_tumor_max_volume_ml": max_volume,
        "n_rows_total": int(len(rows)),
        "n_rows_used": int(len(tumor_rows)),
        "texture_support": texture_support,
    }

    if max_volume is not None:
        if max_volume >= threshold:
            predicted = "HGG"
    else:
        # Fallback when volume is unavailable: any rich texture evidence -> HGG.
        if int(texture_support.get("available_count") or 0) >= 2:
            predicted = "HGG"
            basis["rule"] = "texture_fallback"

    confidence = 0.60
    if max_volume is not None and threshold > 0:
        margin = abs(max_volume - threshold) / threshold
        confidence = min(0.95, 0.60 + min(0.25, 0.45 * margin))
    texture_bonus = min(0.10, 0.03 * int(texture_support.get("available_count") or 0))
    confidence = min(0.95, float(confidence + texture_bonus))

    output_subdir = str(args.get("output_subdir") or "classification/brain_grade").strip() or "classification/brain_grade"
    out_dir = ctx.artifacts_dir / output_subdir
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path_arg = str(args.get("classification_path") or "").strip()
    if out_path_arg:
        out_path = Path(out_path_arg).expanduser().resolve()
        out_path.parent.mkdir(parents=True, exist_ok=True)
    else:
        out_path = out_dir / "brain_glioma_grade.json"

    payload = {
        "predicted_grade": predicted,
        "confidence": round(float(confidence), 3),
        "decision_basis": basis,
        "source_feature_table_path": str(feature_path),
    }
    out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    artifacts = [
        ArtifactRef(
            path=str(out_path),
            kind="json",
            description=f"Brain glioma grade classification ({predicted})",
        )
    ]
    return {
        "ok": True,
        "data": {
            "classification_path": str(out_path),
            "predicted_grade": predicted,
            "confidence": float(round(confidence, 3)),
            "decision_basis": basis,
        },
        "generated_artifacts": artifacts,
    }


def build_tool() -> Tool:
    return Tool(spec=BRAIN_GRADE_SPEC, func=classify_brain_glioma_grade)
